# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-27 05:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_auto_20160526_2255'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'verbose_name': 'Cliente', 'verbose_name_plural': 'Clientes'},
        ),
        migrations.RemoveField(
            model_name='customer',
            name='customerpnumber',
        ),
    ]
