# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-27 04:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeposition',
            name='end',
            field=models.TimeField(help_text='Ingrese el Horario de fin de labores de este cargo', verbose_name='Hora de Salida'),
        ),
        migrations.AlterField(
            model_name='employeeposition',
            name='start',
            field=models.TimeField(help_text='Ingrese el Horario de inicio de labores de este cargo', verbose_name='Hora de Entrada'),
        ),
    ]
