# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-27 04:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_auto_20160526_2241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='position',
            field=models.ForeignKey(help_text='Selccione el Cargo o puesto que el empleado Ocupar\xe1', on_delete=django.db.models.deletion.CASCADE, to='employee.EmployeePosition', verbose_name='Puesto/Cargo'),
        ),
    ]
