# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-27 04:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('comon', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('person_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='comon.Person')),
                ('phonenumber', models.IntegerField(help_text='Ingrese un N\xfamero para contactar al empleado', verbose_name='N\xfamero de Contacto')),
            ],
            options={
                'verbose_name': 'Empleado',
                'verbose_name_plural': 'Empleados',
            },
            bases=('comon.person',),
        ),
        migrations.CreateModel(
            name='EmployeePosition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(help_text='Ingrese el nombre del cargo o puesto a crear', max_length=50, verbose_name='Nombre del Cargo')),
                ('salary', models.FloatField(help_text='Ingrese el monto a devengar en este puesto', max_length=7, verbose_name='Salario del Puesto')),
                ('start', models.TimeField(verbose_name='Hora de Entrada')),
                ('end', models.TimeField(verbose_name='Hora de Salida')),
            ],
            options={
                'verbose_name': 'Puesto',
                'verbose_name_plural': 'Puestos',
            },
        ),
        migrations.AddField(
            model_name='employee',
            name='position',
            field=models.ForeignKey(help_text='Ingrese el Cargo o puesto que el empleado Ocupar\xe1', on_delete=django.db.models.deletion.CASCADE, to='employee.EmployeePosition', verbose_name='Puesto/Cargo'),
        ),
    ]
