# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-27 04:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(help_text='Ingrese Nombre', max_length=20, verbose_name='Nombre')),
                ('last_name', models.CharField(help_text='Ingrese Aepllido', max_length=20, verbose_name='Apellido')),
                ('address', models.CharField(help_text='Ingrese Direcci\xf3n', max_length=50, verbose_name='Direcci\xf3n')),
                ('birthday', models.DateField(help_text='Ingrese Fecha de Nacimiento', verbose_name='Fecha de Nacimiento')),
                ('nit', models.IntegerField(help_text='Ingrese Numero De Identificaci\xf3n Tributaria', verbose_name='Nit')),
                ('gender', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], default='M', help_text='Selecci\xf3n de G\xe9nero', max_length=1, verbose_name='Genero')),
            ],
        ),
    ]
