# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-27 04:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('comon', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('person_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='comon.Person')),
                ('customerpnumber', models.IntegerField(help_text='Ingrese un N\xfamero para poder contactar al cliente', verbose_name='N\xfamero de Contacto')),
            ],
            bases=('comon.person',),
        ),
        migrations.CreateModel(
            name='CustomerType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('A', 'FRECUENTE'), ('B', 'REGULAR'), ('C', 'NORMAL')], default='C', help_text='Selecci\xf3n de Tipo de Cliente', max_length=1, verbose_name='Tipo de Cliente')),
            ],
        ),
    ]
