# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-27 04:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomerType',
        ),
        migrations.AddField(
            model_name='customer',
            name='discount',
            field=models.CharField(choices=[('0.01', 'Minorista'), ('0.05', 'Frecuente'), ('0.10', 'Mayorista')], default='0.01', max_length=5, verbose_name='Descuento'),
        ),
    ]
